MODEL:
  META_ARCHITECTURE: "CenterNet"
  PIXEL_MEAN: [0.408, 0.447, 0.470]
  PIXEL_STD: [0.289, 0.274, 0.278]
DATASETS:
  TRAIN: ("bulb_wise_tl_train",)
  TEST: ("bulb_wise_tl_train",)
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 2.5e-4
  STEPS: (79500, 106000)
  MAX_ITER: 132500
  CHECKPOINT_PERIOD: 5300
#TEST:
#  EVAL_PERIOD: 1
OUTPUT_DIR: "./output/centernet-bulb-finetune-0706-debug"
VERSION: 2