MODEL:
  META_ARCHITECTURE: "CenterNet"
  PIXEL_MEAN: [0.408, 0.447, 0.470]
  PIXEL_STD: [0.289, 0.274, 0.278]
  WEIGHTS: '/autox-sz/users/chenxiaoniu/centernet_init.pth'
DATASETS:
  TRAIN: ("bulb_wise_tl_train",)
  TEST: ("bulb_wise_tl_train",)
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 2.5e-4  # Note that RetinaNet uses a different default learning rate
  STEPS: (60000, 80000)
  MAX_ITER: 100000
  CHECKPOINT_PERIOD: 4000
#TEST:
#  EVAL_PERIOD: 60
INPUT:
  FIX_SIZE: True
  FIX_SIZE_H: 768
  FIX_SIZE_W: 1280
  HM: True
OUTPUT_DIR: "./output/centernet-bulb"
VERSION: 2