MODEL:
  META_ARCHITECTURE: "CenterNet"
DATASETS:
  TRAIN: ("bulb_wise_tl_train",)
  TEST: ("bulb_wise_tl_train",)
SOLVER:
  IMS_PER_BATCH: 4
  BASE_LR: 0.01  # Note that RetinaNet uses a different default learning rate
  STEPS: (60000, 80000)
  MAX_ITER: 90000
INPUT:
  FIX_SIZE: True
  FIX_SIZE_H: 768
  FIX_SIZE_W: 1280
  HM: True
OUTPUT_DIR: "./output/centernet-bulb"
VERSION: 2