_BASE_: "./Base-CenterNet.yaml"
MODEL:
  CENTERNET:
    FOCAL_LOSS_ALPHA: [1]
DATASETS:
  TRAIN: ("sz_sh_bulb_train",)
  TEST: ("sz_sh_bulb_val",)
INPUT:
  FORMAT: "RGB"
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 2.5e-4
  STEPS: (159000, 212000)
  MAX_ITER: 265000
  CHECKPOINT_PERIOD: 10600
#TEST:
#  EVAL_PERIOD: 1
OUTPUT_DIR: "./output/centernet-bulb-aug"
VERSION: 2
