_BASE_: "./Base-CenterNet.yaml"
MODEL:
  BACKBONE:
    NAME: "build_vovnet_backbone"
  WEIGHTS: "/autox-sz/users/chenxiaoniu/models/vovnet19_ese_slim_detectron2.pth"
  VOVNET:
    OUT_FEATURES: ["stage2", "stage3", "stage4", "stage5"]
    CONV_BODY: "V-19-slim-eSE"
  CENTERNET:
    HEAD_CONV: 64
    FOCAL_LOSS_ALPHA: [1]
DATASETS:
  TRAIN: ("bulb_train",)
  TEST: ("bulb_val",)
INPUT:
  FORMAT: "RGB"
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
SOLVER:
  IMS_PER_BATCH: 24
  BASE_LR: 2.5e-4
  STEPS: (136500, 273000)
  MAX_ITER: 364000
  CHECKPOINT_PERIOD: 3640
TEST:
  EVAL_PERIOD: 1820
OUTPUT_DIR: "./output/centernet-vovnet19-slim-bulb"
VERSION: 2