_BASE_: "./Base-CenterNet.yaml"
MODEL:
  BACKBONE:
    NAME: "build_resnet_backbone"
  CENTERNET:
    FOCAL_LOSS_ALPHA: [1]
    HEAD_CONV: 64
  RESNETS:
    DEPTH: 18
    RES2_OUT_CHANNELS: 64
    NORM: "SyncBN"
DATASETS:
  TRAIN: ("class_agnostic_bulb_train",)
  TEST: ("class_agnostic_bulb_val",)
INPUT:
  FORMAT: "RGB"
  MAX_SIZE_TRAIN: 1920
  MIN_SIZE_TRAIN: (672, 736, 800, 864, 928, 992, 1056)
  MAX_SIZE_TEST: 1920
  MIN_SIZE_TEST: 1056
SOLVER:
  IMS_PER_BATCH: 24
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  BASE_LR: 2.5e-4
  MAX_ITER: 364000
  CHECKPOINT_PERIOD: 3640
TEST:
  EVAL_PERIOD: 1820
OUTPUT_DIR: "./output/class_agnostic_large"
VERSION: 2