_BASE_: "./Base-CenterNet.yaml"
MODEL:
  BACKBONE:
    NAME: "build_vovnet_backbone"
  VOVNET:
    OUT_FEATURES: ["stage2", "stage3", "stage4", "stage5"]
  CENTERNET:
    FOCAL_LOSS_ALPHA: [1]
DATASETS:
  TRAIN: ("sz_sh_bulb_train",)
  TEST: ("sz_sh_bulb_train",)
INPUT:
  FORMAT: "RGB"
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
SOLVER:
  IMS_PER_BATCH: 12
  BASE_LR: 2.5e-4
  STEPS: (220000, 330000)
  MAX_ITER: 440000
  CHECKPOINT_PERIOD: 8800
TEST:
  EVAL_PERIOD: 18008
OUTPUT_DIR: "./output/centernet-vovnet19-bulb"
VERSION: 2
