_BASE_: "./Base-CenterNet.yaml"
MODEL:
  BACKBONE:
    NAME: "build_resnet_backbone"
  CENTERNET:
    FOCAL_LOSS_ALPHA: [1]
    HEAD_CONV: 64
  RESNETS:
    DEPTH: 34
    RES2_OUT_CHANNELS: 64
DATASETS:
  TRAIN: ("bulb_train",)
  TEST: ("bulb_val",)
INPUT:
  FORMAT: "RGB"
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
SOLVER:
  IMS_PER_BATCH: 24
  BASE_LR: 2.5e-4
  STEPS: (136500, 273000)
  MAX_ITER: 364000
  CHECKPOINT_PERIOD: 3640
TEST:
  EVAL_PERIOD: 1820
OUTPUT_DIR: "./output"
VERSION: 2