_BASE_: "./Base-CenterNet.yaml"
MODEL:
  BACKBONE:
    NAME: "build_resnet_backbone"
  CENTERNET:
    FOCAL_LOSS_ALPHA: [1]
DATASETS:
  TRAIN: ("bulb_train",)
  TEST: ("bulb_val",)
INPUT:
  FORMAT: "RGB"
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
SOLVER:
  IMS_PER_BATCH: 2
  BASE_LR: 2.5e-4
  STEPS: (225100, 337650)
  MAX_ITER: 450200
  CHECKPOINT_PERIOD: 9004
TEST:
  EVAL_PERIOD: 18008
OUTPUT_DIR: "./output"
VERSION: 2
